services:
  api:
    build:
      context: .
      target: final
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Container 
   
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
  reacr_client:
    build:
      context: https://github.com/TRPZtest/quizClient.git       
    ports:
      - 3000:3000
